version: "3"
services:
  nginx:
    image: nginx:alpine
    container_name: dnmp-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./www/:/var/www/html/:rw
      - ./conf/conf.d:/etc/nginx/conf.d/:ro
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./log/:/var/log/dnmp/:rw
    networks:
      - net-php

  php:
    build: ./php/php72/
    container_name: dnmp-php
    expose:
      - "9000"
    volumes:
      - ./www/:/var/www/html/:rw
      - ./conf/php.ini:/usr/local/etc/php/php.ini:ro
      - ./conf/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf:rw
      - ./log/:/var/log/dnmp/:rw
    networks:
      - net-php
      - net-mysql
      - net-redis
      - net-rabbit
      - net-esnet

  mysql:
    image: mysql:8.0.11
    container_name: dnmp-mysql
    ports:
      - "3306:3306"
    volumes:
      - ./conf/my.cnf:/etc/mysql/my.cnf:ro
      - ./mysql/:/var/lib/mysql/:rw
      - ./log/:/var/log/dnmp/:rw
    networks:
      - net-mysql
    environment:
      MYSQL_ROOT_PASSWORD: "qwermysql"

  redis:
    image: redis:4.0
    container_name: dnmp-redis
    networks:
      - net-redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3.7.6-management
    container_name: dnmp-rabbitmq
    hostname: rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./conf/rabbitmq.cnf:/etc/rabbitmq/rabbitmq.cnf:ro
      - ./rabbitmq/:/var/lib/rabbitmq/:rw
      - ./log/:/var/log/dnmp/:rw      
    networks:
      - net-rabbit
    environment:
      RABBITMQ_DEFAULT_USER: "user"
      RABBITMQ_DEFAULT_PASS: "123456" 

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.1
    container_name: elasticsearch
    environment:
      - cluster.name=wufly
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - net-esnet
  elasticsearch2:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.1
    container_name: elasticsearch2
    environment:
      - cluster.name=wufly
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata2:/usr/share/elasticsearch/data
    networks:
      - net-esnet

networks:
  net-php:
  net-mysql:
  net-redis:
  net-rabbit:
  net-esnet:
volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local